name: measurements
description: A new flutter plugin project.
version: 0.0.1
author: arconsis IT-Solutions GmbH
homepage: "https://github.com/ChristianNavolskyi/measurements"

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  equatable: 1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: 3.2.0
  get_it: 4.0.1
  image: 2.1.4
  path_provider: 1.6.5
  rxdart: 0.23.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    androidPackage: com.arconsis.measurements
    pluginClass: MeasurementsPlugin
