name: measurements
description: A widget that allows you to measure distances in documents.
version: 0.0.1
repository: "https://github.com/arconsis/measurements"
issue_tracker: "https://github.com/arconsis/measurements/issues"

environment:
  sdk: ^2.6.0
  flutter: ^1.12.0

dependencies:
  equatable: ^1.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^5.0.1
  get_it: ^4.0.4
  meta: ^1.1.8
  path_provider: ^1.6.11
  rxdart: ^0.24.1

dev_dependencies:
  bloc_test: 6.0.1
  flutter_test:
    sdk: flutter
  mockito: 4.1.1

flutter:
  plugin:
    platforms:
      android:
        package: com.arconsis.measurements
        pluginClass: MeasurementsPlugin
      ios:
        pluginClass: MeasurementsPlugin

