name: measurements
description: A widget that allows you to measure distances in documents.
version: 0.0.1
author: arconsis IT-Solutions GmbH
homepage: "https://github.com/arconsis/measurements"

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  equatable: 1.2.2
  flutter:
    sdk: flutter
  flutter_bloc: 5.0.1
  get_it: 4.0.2
  image: 2.1.12
  meta: 1.1.8
  path_provider: 1.6.11
  rxdart: 0.24.1

dev_dependencies:
  bloc_test: 6.0.1
  flutter_test:
    sdk: flutter
  mockito: 4.1.1

flutter:
  plugin:
    androidPackage: com.arconsis.measurements
    pluginClass: MeasurementsPlugin
